name: Build

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Check spotless
        run: ./gradlew spotlessCheck --no-configuration-cache
      - name: Execute Gradle build
        run: ./gradlew clean build
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build APK
        run: ./gradlew :app:assembleDebug
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload build outputs (APK)
        uses: actions/upload-artifact@v4
        with:
          name: radio_capullo-${{ github.sha }}
          path: '**/build/outputs/apk/debug/*.apk'