name: Build Gradle project

on:
  push:
    tags:
      - '*'

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build APK
        run: ./gradlew :app:assembleDebug
      #- name: release
      #  uses: actions/create-release@v1
      #  id: create_release
      #  with:
      #    draft: false
      #    prerelease: false
      #    release_name: ${{ github.ref }}
      #    tag_name: ${{ github.ref }}
      #  env:
      #    GITHUB_TOKEN: ${{ github.token }}
      - name: Update Artifact
        uses: actions/upload-artifact@v3
        with:
          path: ./app/build/outputs/apk/debug/app-debug.apk
          name: app-debug.apk