name: Build Gradle project

on:
  push:
    #tags:
      #- '*'

permissions:
  contents: write


jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build APK
        run: ./gradlew :app:assembleDebug
      - name: Create Release
        run: |
          tag=$(git describe --tags --abbrev=0)
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --generate-notes
      - name: Update Artifact
        uses: actions/upload-artifact@v3
        with:
          path: ./app/build/outputs/apk/debug/app-debug.apk
          name: app-debug.apk