name: Build

on:
  pull_request:
    branches:
      - develop
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/release' }}
      - name: Execute Gradle build
        run: ./gradlew build
      - name: Build APK
        run: ./gradlew :app:assembleDebug
      - name: Upload build outputs (APKs)
        uses: actions/upload-artifact@v4
        with:
          name: radio_capullo-${{ github.run_number }}
          path: '**/build/outputs/apk/debug/*.apk'
  publish-release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') && github.ref == 'refs/heads/release'
    steps:
      - name: Download APK artifact
        uses: actions/download-artifact@v4
        with:
          name: radio_capullo-${{ github.run_number }}
      - name: Create Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          tag=$(git describe --tags --abbrev=0)
          gh release create "$tag" \
              --generate-notes
      - name: Upload Release Asset
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          tag=$(git describe --tags --abbrev=0)
          gh release upload "$tag" "radio_capullo-${{ github.run_number }}#radio_capullo-$tag.apk"