name: GitHub Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build APK
        run: ./gradlew :app:assembleDebug
      - name: Create Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          tag=$(git describe --tags --abbrev=0)
          gh release create "$tag" \
              --generate-notes
      - name: Upload Release Asset
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          tag=$(git describe --tags --abbrev=0)
          gh release upload "$tag" "./build/outputs/apk/debug/app_debug.apk#radio_capullo-$tag.apk"